/**
 * Golden-master characterization tests for scoreFromData.
 *
 * PURPOSE: Lock current observable outputs before any refactoring of the
 * scoreFromData body. All structural invariants (field presence, types,
 * value ranges, signal consistency with score) are checked here.
 * Behavioural snapshots live in the companion .snap file generated by
 * node --test --test-update-snapshots on first run.
 *
 * HOW TO UPDATE SNAPSHOTS:
 *   node --test --test-update-snapshots tests/scoring-golden.test.js
 */

import assert from "node:assert/strict";
import test, { snapshot } from "node:test";
import { scoreFromData } from "../bot/scoring.js";

// ── Snapshot file location (sibling to this test file) ───────────────────────
snapshot.setResolveSnapshotPath((testFile) =>
  testFile.replace(/\.test\.js$/, ".snap.cjs")
);

// ── Deterministic candle factories ───────────────────────────────────────────
// All candles use a fixed seed so runs are identical.
// Each factory models a distinct market structure used by scoreFromData branches.

function makeUptrend(count, { start = 100, stepBase = 0.25, vol = 5000 } = {}) {
  const candles = [];
  let close = start;
  for (let i = 0; i < count; i++) {
    close += stepBase + Math.sin(i / 6) * stepBase * 0.15;
    const open = close - stepBase * 0.3;
    const high = close + stepBase * 0.8;
    const low  = open  - stepBase * 0.2;
    candles.push({ time: i * 3600000, open, high, low, close: Math.max(low + 0.01, close), volume: vol + i * 2 });
  }
  return candles;
}

function makeDowntrend(count, { start = 200, stepBase = 0.25, vol = 5000 } = {}) {
  const candles = [];
  let close = start;
  for (let i = 0; i < count; i++) {
    close -= stepBase + Math.sin(i / 6) * stepBase * 0.15;
    if (close < 1) close = 1;
    const open = close + stepBase * 0.3;
    const high = open  + stepBase * 0.2;
    const low  = close - stepBase * 0.8;
    candles.push({ time: i * 3600000, open, high, low, close: Math.max(0.01, close), volume: vol + i * 2 });
  }
  return candles;
}

function makeFlat(count, { center = 150, swing = 0.4, vol = 4000 } = {}) {
  const candles = [];
  for (let i = 0; i < count; i++) {
    const close = center + Math.sin(i / 12) * swing;
    const open  = center + Math.sin((i - 1) / 12) * swing;
    const high  = Math.max(open, close) + 0.15;
    const low   = Math.min(open, close) - 0.15;
    candles.push({ time: i * 3600000, open, high, low, close, volume: vol + (i % 7) * 50 });
  }
  return candles;
}

function makeChoppy(count, { center = 100, amp = 2, vol = 3000 } = {}) {
  const candles = [];
  for (let i = 0; i < count; i++) {
    const noise = Math.sin(i * 1.7) * amp + Math.cos(i * 0.9) * amp * 0.5;
    const close = center + noise;
    const open  = center + Math.sin((i - 1) * 1.7) * amp;
    const high  = Math.max(open, close) + 0.3;
    const low   = Math.min(open, close) - 0.3;
    candles.push({ time: i * 3600000, open, high, low, close: Math.max(0.01, close), volume: vol });
  }
  return candles;
}

const mockState = {
  dynamicWeights: {},
  signalStats: {},
  disabledSignals: [],
  positions: {}
};

// ── Structural invariant helper ────────────────────────────────────────────────
function assertCandidateShape(result, label) {
  if (result === null) return; // null is always valid; no structural assertions needed
  assert.equal(typeof result.signal,    "string",  `${label}: signal must be string`);
  assert.ok(["long", "short"].includes(result.signal), `${label}: signal must be long|short`);
  assert.equal(typeof result.score,     "number",  `${label}: score must be number`);
  assert.ok(result.score >= 0,                     `${label}: score >= 0`);
  assert.equal(typeof result.setupType, "string",  `${label}: setupType must be string`);
  assert.ok(Array.isArray(result.reasons),         `${label}: reasons must be array`);
  assert.equal(typeof result.price,     "number",  `${label}: price must be number`);
  assert.ok(result.price > 0,                      `${label}: price > 0`);
  assert.equal(typeof result.sl,        "number",  `${label}: sl must be number`);
  assert.equal(typeof result.tp,        "number",  `${label}: tp must be number`);
  if (result.signal === "long") {
    assert.ok(result.sl < result.price,  `${label}: long sl < price`);
    assert.ok(result.tp > result.price,  `${label}: long tp > price`);
  } else {
    assert.ok(result.sl > result.price,  `${label}: short sl > price`);
    assert.ok(result.tp < result.price,  `${label}: short tp < price`);
  }
  assert.ok(result.riskReward > 0,                 `${label}: riskReward > 0`);
  assert.equal(typeof result.atrVal,    "number",  `${label}: atrVal must be number`);
  assert.ok(result.atrVal > 0,                     `${label}: atrVal > 0`);
  assert.ok(["bullish","bearish","neutral"].includes(result.h4Trend), `${label}: h4Trend valid`);
}

// ── Snapshot helper: strips non-deterministic fields before comparison ────────
function snapshotable(result) {
  if (!result) return null;
  const { _candles1h: _c, _srLevels: _s, ...rest } = result;
  return {
    ...rest,
    reasons: [...rest.reasons].sort(),
    score: Math.round(rest.score * 10) / 10,
    sl: Math.round(rest.sl * 1000) / 1000,
    tp: Math.round(rest.tp * 1000) / 1000,
    riskReward: Math.round(rest.riskReward * 100) / 100,
    price: Math.round(rest.price * 1000) / 1000,
    atrVal: Math.round(rest.atrVal * 1000) / 1000,
    vwapVal: Math.round(rest.vwapVal * 1000) / 1000,
    ema21: rest.ema21 != null ? Math.round(rest.ema21 * 1000) / 1000 : null,
  };
}

// ── Tests ──────────────────────────────────────────────────────────────────────

test("scoreFromData - null for insufficient data", () => {
  const s = mockState;
  assert.equal(scoreFromData("X", null,  [],            { label: "bull" }, s), null);
  assert.equal(scoreFromData("X", [],    [],            { label: "bull" }, s), null);
  assert.equal(scoreFromData("X", makeUptrend(50), [],  { label: "bull" }, s), null);
});

test("scoreFromData - bull regime strong uptrend shape", (t) => {
  const c1h = makeUptrend(620);
  const c4h = makeUptrend(220, { stepBase: 0.5 });
  const result = scoreFromData("TEST-USDT-SWAP", c1h, c4h, { label: "bull" }, mockState);
  assertCandidateShape(result, "bull-uptrend");
  t.assert.snapshot(snapshotable(result));
});

test("scoreFromData - bear regime strong downtrend shape", (t) => {
  const c1h = makeDowntrend(620);
  const c4h = makeDowntrend(220, { stepBase: 0.5 });
  const result = scoreFromData("ALT-USDT-SWAP", c1h, c4h, { label: "bear" }, mockState);
  assertCandidateShape(result, "bear-downtrend");
  t.assert.snapshot(snapshotable(result));
});

test("scoreFromData - sideways regime flat shape", (t) => {
  const c1h = makeFlat(620);
  const c4h = makeFlat(220);
  const result = scoreFromData("ALT-USDT-SWAP", c1h, c4h, { label: "sideways" }, mockState);
  assertCandidateShape(result, "sideways-flat");
  t.assert.snapshot(snapshotable(result));
});

test("scoreFromData - chop regime returns null or very selective", () => {
  const c1h = makeChoppy(620);
  const c4h = makeChoppy(220);
  const result = scoreFromData("CHOP-USDT-SWAP", c1h, c4h, { label: "chop" }, mockState);
  // chop regime requires minDiff=1.5 and baseMinScore=4 — expect null or valid candidate
  if (result !== null) assertCandidateShape(result, "chop");
});

test("scoreFromData - deterministic across two identical calls", () => {
  const c1h = makeUptrend(620, { start: 75, stepBase: 0.18 });
  const c4h = makeUptrend(220, { start: 75, stepBase: 0.45 });
  const regime = { label: "bull" };
  const r1 = scoreFromData("DET-USDT-SWAP", c1h, c4h, regime, mockState);
  const r2 = scoreFromData("DET-USDT-SWAP", c1h, c4h, regime, mockState);
  assert.deepEqual(snapshotable(r1), snapshotable(r2));
});

test("scoreFromData - disabled signals excluded from reasons", () => {
  const c1h = makeUptrend(620);
  const c4h = makeUptrend(220, { stepBase: 0.5 });
  const stateWithDisabled = {
    ...mockState,
    disabledSignals: ["ema-ribbon-bull", "h4-bull", "h4-bull-pb"]
  };
  const result = scoreFromData("TEST-USDT-SWAP", c1h, c4h, { label: "bull" }, stateWithDisabled);
  if (result) {
    assert.ok(!result.reasons.includes("ema-ribbon-bull"), "disabled signal must not appear");
    assert.ok(!result.reasons.includes("h4-bull"),         "disabled signal must not appear");
  }
});

test("scoreFromData - score exhaustion caps above 7", () => {
  // Highly trending candles in bull regime should be capped at 7 + (excess * 0.5)
  const c1h = makeUptrend(620, { stepBase: 0.6, vol: 20000 });
  const c4h = makeUptrend(220, { stepBase: 1.2, vol: 30000 });
  const result = scoreFromData("TEST-USDT-SWAP", c1h, c4h, { label: "bull" }, mockState);
  if (result) {
    // Raw pre-exhaustion score could have been >> 7; after exhaustion it should be <= ~10
    assert.ok(result.score <= 12, "score should not explode past exhaustion cap");
  }
});

test("scoreFromData - BTC gets 0.5x positionSizeMultiplier in non-strong trend", (t) => {
  const c1h = makeFlat(620, { center: 30000, swing: 150 });
  const c4h = makeFlat(220, { center: 30000, swing: 300 });
  const result = scoreFromData("BTC-USDT-SWAP", c1h, c4h, { label: "sideways" }, mockState);
  if (result) {
    // High-cap penalty applies in non-strong-trend non-bear: multiplier <= 0.5
    assert.ok(result.positionSizeMultiplier <= 0.5 * 1.26,
      `BTC positionSizeMultiplier should reflect high-cap penalty, got ${result.positionSizeMultiplier}`);
  }
  t.assert.snapshot(snapshotable(result));
});
